INSERT INTO vets VALUES (default, 'James', 'Carter');
INSERT INTO vets VALUES (default, 'Helen', 'Leary');
INSERT INTO vets VALUES (default, 'Linda', 'Douglas');
INSERT INTO vets VALUES (default, 'Rafael', 'Ortega');
INSERT INTO vets VALUES (default, 'Henry', 'Stevens');
INSERT INTO vets VALUES (default, 'Sharon', 'Jenkins');

INSERT INTO specialties VALUES (default, 'radiology');
INSERT INTO specialties VALUES (default, 'surgery');
INSERT INTO specialties VALUES (default, 'dentistry');

INSERT INTO vet_specialties VALUES (2, 1);
INSERT INTO vet_specialties VALUES (3, 2);
INSERT INTO vet_specialties VALUES (3, 3);
INSERT INTO vet_specialties VALUES (4, 2);
INSERT INTO vet_specialties VALUES (5, 1);

INSERT INTO types VALUES (default, 'cat');
INSERT INTO types VALUES (default, 'dog');
INSERT INTO types VALUES (default, 'lizard');
INSERT INTO types VALUES (default, 'snake');
INSERT INTO types VALUES (default, 'bird');
INSERT INTO types VALUES (default, 'hamster');

INSERT INTO owners VALUES (default, 'George', 'Franklin', '110 W. Liberty St.', 'Madison', '6085551023');
INSERT INTO owners VALUES (default, 'Betty', 'Davis', '638 Cardinal Ave.', 'Sun Prairie', '6085551749');
INSERT INTO owners VALUES (default, 'Eduardo', 'Rodriquez', '2693 Commerce St.', 'McFarland', '6085558763');
INSERT INTO owners VALUES (default, 'Harold', 'Davis', '563 Friendly St.', 'Windsor', '6085553198');
INSERT INTO owners VALUES (default, 'Peter', 'McTavish', '2387 S. Fair Way', 'Madison', '6085552765');
INSERT INTO owners VALUES (default, 'Jean', 'Coleman', '105 N. Lake St.', 'Monona', '6085552654');
INSERT INTO owners VALUES (default, 'Jeff', 'Black', '1450 Oak Blvd.', 'Monona', '6085555387');
INSERT INTO owners VALUES (default, 'Maria', 'Escobito', '345 Maple St.', 'Madison', '6085557683');
INSERT INTO owners VALUES (default, 'David', 'Schroeder', '2749 Blackhawk Trail', 'Madison', '6085559435');
INSERT INTO owners VALUES (default, 'Carlos', 'Estaban', '2335 Independence La.', 'Waunakee', '6085555487');

INSERT INTO pets VALUES (default, 'Leo', '2010-09-07', 1, 1);
INSERT INTO pets VALUES (default, 'Basil', '2012-08-06', 6, 2);
INSERT INTO pets VALUES (default, 'Rosy', '2011-04-17', 2, 3);
INSERT INTO pets VALUES (default, 'Jewel', '2010-03-07', 2, 3);
INSERT INTO pets VALUES (default, 'Iggy', '2010-11-30', 3, 4);
INSERT INTO pets VALUES (default, 'George', '2010-01-20', 4, 5);
INSERT INTO pets VALUES (default, 'Samantha', '2012-09-04', 1, 6);
INSERT INTO pets VALUES (default, 'Max', '2012-09-04', 1, 6);
INSERT INTO pets VALUES (default, 'Lucky', '2011-08-06', 5, 7);
INSERT INTO pets VALUES (default, 'Mulligan', '2007-02-24', 2, 8);
INSERT INTO pets VALUES (default, 'Freddy', '2010-03-09', 5, 9);
INSERT INTO pets VALUES (default, 'Lucky', '2010-06-24', 2, 10);
INSERT INTO pets VALUES (default, 'Sly', '2012-06-08', 1, 10);

INSERT INTO visits VALUES (default, 7, '2013-01-01', 'rabies shot');
INSERT INTO visits VALUES (default, 8, '2013-01-02', 'rabies shot');
INSERT INTO visits VALUES (default, 8, '2013-01-03', 'neutered');
INSERT INTO visits VALUES (default, 7, '2013-01-04', 'spayed');

INSERT INTO books VALUES (default, 'Maira Kalman', 'Beloved Dog', 'dog', '2017-10-31', 'Penguin', '162');
INSERT INTO books VALUES (default, 'Sophie Gamand', 'Wet Dog', 'dog', '2015-10-13', 'Grand Central Publishing', '153');
INSERT INTO books VALUES (default, 'Alexandra Horowitz', 'Inside of a Dog', 'dog', '2010-02-18', 'Simon and Schuster', '313');
INSERT INTO books VALUES (default, 'Sara Carson', 'Super Dog Tricks', 'dog', '2021-11-02', 'Quarry Books', '178');
INSERT INTO books VALUES (default, 'Bromfield Press', 'Ivy the Very Determined Dog', 'dog', '1919-04', 'Unknown', '0');
INSERT INTO books VALUES (default, 'Larry Kay', 'The Big Book of Tricks for the Best Dog Ever', 'dog', '2019-03-19', 'Workman Publishing', '321');
INSERT INTO books VALUES (default, 'Rodney Habib', 'The Forever Dog', 'dog', '2021-10-12', 'HarperCollins', '335');
INSERT INTO books VALUES (default, 'The American Kennel Club', 'The New Complete Dog Book', 'dog', '2017-08-01', 'Fox Chapel Publishing', '1401');
INSERT INTO books VALUES (default, 'P.D. Eastman', 'Go, Dog. Go!', 'dog', '2015-08-25', 'Random House Books for Young Readers', '24');
INSERT INTO books VALUES (default, 'Jon Katz', 'A Good Dog', 'dog', '2006-11-28', 'Villard', '192');
INSERT INTO books VALUES (default, 'Laura T. Coffey', 'My Old Dog', 'dog', '2015-09-18', 'New World Library', '258');
INSERT INTO books VALUES (default, 'Randal Ford', 'Good Dog', 'dog', '2020-10-06', 'Rizzoli Publications', '210');
INSERT INTO books VALUES (default, 'Sharon Creech', 'Love That Dog', 'dog', '2014-12-23', 'Harper Collins', '132');
INSERT INTO books VALUES (default, 'Rachel Mannheimer', 'Earth Room', 'dog', '2022-04-05', 'Unknown', '80');
INSERT INTO books VALUES (default, 'Mônica Carnesi', 'Little Dog Lost', 'dog', '2022-02-22', 'Penguin', '41');
INSERT INTO books VALUES (default, 'Bénédicte Boisseron', 'Afro-Dog', 'dog', '2018-08-14', 'Columbia University Press', '234');
INSERT INTO books VALUES (default, 'Lamar Underwood', 'Dog Tales', 'dog', '2022-11-01', 'Rowman & Littlefield', '375');
INSERT INTO books VALUES (default, 'Louise Glazebrook', 'The Book Your Dog Wishes You Would Read', 'dog', '2021-11-18', 'Hachette UK', '166');
INSERT INTO books VALUES (default, 'The American Kennel Club', 'The New Complete Dog Book', 'dog', '2014-11-11', 'i5 Publishing', '914');
INSERT INTO books VALUES (default, 'Clive D. L. Wynne', 'Dog is Love', 'dog', '2019', 'Mariner Books', '277');
INSERT INTO books VALUES (default, 'J. H. Lee', 'Boo', 'dog', '2011-06-24', 'Chronicle Books', '80');
INSERT INTO books VALUES (default, 'Judith Henderson', 'This Is a Dog Book!', 'dog', '2021-06-01', 'Kids Can Press Ltd', '44');
INSERT INTO books VALUES (default, 'Jan Allegretti', 'The Complete Holistic Dog Book', 'dog', '2013-10-15', 'Celestial Arts', '385');
INSERT INTO books VALUES (default, 'John W. Pilley', 'Chaser', 'dog', '2013', 'Houghton Mifflin Harcourt', '285');
INSERT INTO books VALUES (default, 'Eric Rohmann', 'Bone Dog', 'dog', '2011-07-19', 'Macmillan', '47');
INSERT INTO books VALUES (default, 'Nancy J. Hajeski', 'Every Dog', 'dog', '2016', 'Unknown', '0');
INSERT INTO books VALUES (default, 'Erika Sargent', 'Dogs Will Be Dogs', 'dog', '2020-10-27', 'Workman Publishing', '78');
INSERT INTO books VALUES (default, 'Matthew Johnstone', 'I Had a Black Dog', 'dog', '2005', 'Pan Australia', '52');
INSERT INTO books VALUES (default, 'DK', 'The Complete Dog Breed Book', 'dog', '2020-03-05', 'Dorling Kindersley Ltd', '352');
INSERT INTO books VALUES (default, 'Robert P Barbieri', 'Dominic the Dog', 'dog', '2020-05-15', 'Unknown', '26');
INSERT INTO books VALUES (default, 'Richard A. Wolters', 'Game Dog', 'dog', '1995-01-01', 'National Geographic Books', '0');
INSERT INTO books VALUES (default, 'McDowell Lyon', 'The Dog in Action', 'dog', 'Unknown', 'Dogwise Publishing', '303');
INSERT INTO books VALUES (default, 'DK', 'The Complete Dog Breed Book', 'dog', '2015-01-01', 'Penguin', '354');
INSERT INTO books VALUES (default, 'Janice Biniok', 'Complete Guide to Dog Training', 'dog', '2016', 'Tfh Publications, Incorporated', '0');
INSERT INTO books VALUES (default, 'Patricia M. Sherwood', 'The Greatest Dog Stories Ever Told', 'dog', '2023-09-14', 'Rowman & Littlefield', '334');
INSERT INTO books VALUES (default, 'Allison Weiss Entrekin', 'For the Love of Dogs', 'dog', '2011-02', 'Triumph Books', '97');
INSERT INTO books VALUES (default, 'Katharine M. Rogers', 'First Friend', 'dog', '2005-08', 'Macmillan', '328');
INSERT INTO books VALUES (default, 'John M. Simon', 'Anti-Aging for Dogs', 'dog', '2024-05-01', 'Macmillan + ORM', '239');
INSERT INTO books VALUES (default, 'Kyra Sundance', 'The Dog Rules', 'dog', '2009-03-10', 'Simon and Schuster', '257');
INSERT INTO books VALUES (default, 'Unknown', 'The Dog Fancier', 'dog', '1924', 'Unknown', '788');
INSERT INTO books VALUES (default, 'Phaea Crede', 'Jet the Cat (Is Not a Cat)', 'cat', '2021-05-01', 'Barefoot Books', '36');
INSERT INTO books VALUES (default, 'John Bradshaw', 'Cat Sense', 'cat', '2013-09-10', 'Basic Books (AZ)', '337');
INSERT INTO books VALUES (default, 'DK', 'The Cat Encyclopedia', 'cat', '2024-03-12', 'Penguin', '322');
INSERT INTO books VALUES (default, 'Jackson Galaxy', 'Total Cat Mojo', 'cat', '2017-10-31', 'Penguin', '385');
INSERT INTO books VALUES (default, 'Lisa Swerling', 'How to Be a Cat', 'cat', '2016-09-20', 'Chronicle Books', '98');
INSERT INTO books VALUES (default, 'Viviane Schwarz', 'There are Cats in this Book', 'cat', '2008', 'Walker', '32');
INSERT INTO books VALUES (default, 'Jess French', 'Cat Chat', 'cat', '2021', 'Unknown', '0');
INSERT INTO books VALUES (default, 'Mordecai Siegal', 'The Cornell Book of Cats', 'cat', '1997', 'Villard Books', '504');
INSERT INTO books VALUES (default, 'Becky Davies', 'How to Make a Book', 'cat', '2023-07-06', 'Unknown', '0');
INSERT INTO books VALUES (default, 'Jim Edgar', 'Bad Cat', 'cat', '2004-01-01', 'Workman Publishing', '256');
INSERT INTO books VALUES (default, 'Kristyn Crow', 'Skeleton Cat', 'cat', '2012', 'Turtleback', '0');
INSERT INTO books VALUES (default, 'Satoshi Kitamura', 'Me and My Cat?', 'cat', '2005-03-01', 'Sunburst', '40');
INSERT INTO books VALUES (default, 'Jackson Galaxy', 'Catification', 'cat', '2014-10-14', 'Penguin', '306');
INSERT INTO books VALUES (default, 'Thomas Stearns Eliot', 'Old Possum''s Book of Practical Cats', 'cat', '2009', 'Houghton Mifflin Harcourt', '80');
INSERT INTO books VALUES (default, 'Polly Faber', 'The Book Cat', 'cat', '2021-08-24', 'Faber & Faber', '147');
INSERT INTO books VALUES (default, 'Stephen G. Gilbert', 'Outline of Cat Anatomy', 'cat', '2000-01-01', 'University of Toronto Press', '102');
INSERT INTO books VALUES (default, 'Tony Johnston', 'Cat, What Is That?', 'cat', '2001-08-01', 'HarperCollins', '32');
INSERT INTO books VALUES (default, 'Susie Yi', 'Cat & Cat Adventures: The Quest for Snacks', 'cat', '2021-09-07', 'HarperCollins', '100');
INSERT INTO books VALUES (default, 'John Bradshaw', 'The Trainable Cat', 'cat', '2016-09-13', 'Basic Books', '354');
INSERT INTO books VALUES (default, 'Eric Litwin', 'Pete the Cat: I Love My White Shoes', 'cat', '2010-12-07', 'Harper Collins', '41');
INSERT INTO books VALUES (default, 'Deborah Underwood', 'Here Comes Valentine Cat', 'cat', '2015-12-22', 'Penguin', '92');
INSERT INTO books VALUES (default, 'Dennis C. Turner', 'The Domestic Cat', 'cat', '2000-06-08', 'Cambridge University Press', '242');
INSERT INTO books VALUES (default, 'Fiona Sunquist', 'The Wild Cat Book', 'cat', '2014-10-02', 'University of Chicago Press', '277');
INSERT INTO books VALUES (default, 'Susan E. Little', 'The Cat', 'cat', '2011-10-14', 'Elsevier Health Sciences', '1426');
INSERT INTO books VALUES (default, 'James Dean', 'Pete the Cat: 5-Minute Pete the Cat Stories', 'cat', '2017-01-03', 'HarperFestival', '0');
INSERT INTO books VALUES (default, 'Ezra Jack Keats', 'Hi, Cat!', 'cat', '1999-06-01', 'Penguin', '41');
INSERT INTO books VALUES (default, 'John Bradshaw', 'The Trainable Cat', 'cat', '2016-08-04', 'Penguin UK', '371');
INSERT INTO books VALUES (default, 'Unknown', 'Inside Cat', 'cat', '2021-10-12', 'Chronicle Books', '41');
INSERT INTO books VALUES (default, 'Sarah Brown', 'The Cat', 'cat', '2020-03-24', 'Princeton University Press', '227');
INSERT INTO books VALUES (default, 'Satoshi Kitamura', 'Me and My Cat?', 'cat', '2001-06-01', 'Unknown', '29');
INSERT INTO books VALUES (default, 'Universe', 'Cats & Books', 'cat', '2022-03-15', 'Rizzoli Publications', '114');
INSERT INTO books VALUES (default, 'Running Press', 'My Cat Book', 'cat', '2018-10-09', 'Running Press Kids', '80');
INSERT INTO books VALUES (default, 'George the Cat, owner of Celia Haddon', 'A Cat''s Guide to Humans', 'cat', '2019-09-19', 'Hachette UK', '201');
INSERT INTO books VALUES (default, 'Theodor Seuss Geisel', 'The Cat in the Hat', 'cat', '2015-01-17', 'Ishi Press', '66');
INSERT INTO books VALUES (default, 'Mudpuppy', 'Music Cats Board Book (2nd Edition)', 'cat', '2025-01-14', 'Unknown', '0');
INSERT INTO books VALUES (default, 'Alan Edwards', 'The Ultimate Encyclopedia of Cats, Cat Breeds & Cat Care', 'cat', '2004', 'Unknown', '264');
INSERT INTO books VALUES (default, 'Alan Edwards', 'The Ultimate Cat Book', 'cat', '2016-10-05', 'Southwater', '0');
INSERT INTO books VALUES (default, 'Kimberly Hutmacher', 'I Want a Cat', 'cat', '2012', 'Capstone', '25');
INSERT INTO books VALUES (default, 'Sophie Blackall', 'Negative Cat', 'cat', '2021-08-31', 'National Geographic Books', '0');
INSERT INTO books VALUES (default, 'Angela Herlihy', 'My First Cat Book', 'cat', '2016-07-14', 'CICO Books', '0');
INSERT INTO books VALUES (default, 'Joel Jensen', 'Tiny Hamster Is a Giant Monster', 'hamster', '2015-06-02', 'Simon and Schuster', '32');
INSERT INTO books VALUES (default, 'Dietlof Reiche', 'I, Freddy', 'hamster', '2005-04-01', 'Turtleback', '201');
INSERT INTO books VALUES (default, 'Silvia Borando Silvia', 'Guinea Pig Book', 'hamster', '2017-01', 'Minibombo', '32');
INSERT INTO books VALUES (default, 'Colleen AF Venable', 'Hamster and Cheese: Book 1', 'hamster', '2013-11-01', 'Graphic Universe ™', '52');
INSERT INTO books VALUES (default, 'Kass Reich', 'This Little Hamster', 'hamster', '2013-10', 'Orca Book Publishers', '25');
INSERT INTO books VALUES (default, 'Devin Scillian', 'Memoirs of a Hamster', 'hamster', '2013-04-15', 'Sleeping Bear Press', '34');
INSERT INTO books VALUES (default, 'Lorna Freytag', 'My Humongous Hamster', 'hamster', '2014-02-25', 'Henry Holt and Company (BYR)', '32');
INSERT INTO books VALUES (default, 'Virginia Parker Guidry', 'Complete Care Made Easy, Hamsters', 'hamster', '2011-10-11', 'Fox Chapel Publishing', '121');
INSERT INTO books VALUES (default, 'Cheryl Klein', 'Hamsters Make Terrible Roommates', 'hamster', '2021-11-02', 'Penguin', '41');
INSERT INTO books VALUES (default, 'Ross Welford', 'Time Traveling with a Hamster', 'hamster', '2016-10-04', 'Schwartz & Wade', '302');
INSERT INTO books VALUES (default, 'Jason Brainard', 'Is a Hamster a Good Pet for Me?', 'hamster', '2019-07-15', 'The Rosen Publishing Group, Inc', '26');
INSERT INTO books VALUES (default, 'H.I. Siegel', 'The Hamster', 'hamster', '2012-12-06', 'Springer Science & Business Media', '448');
INSERT INTO books VALUES (default, 'Kimberly Hutmacher', 'I Want a Hamster', 'hamster', '2012', 'Capstone', '25');
INSERT INTO books VALUES (default, 'RSPCA', 'Care for Your Hamster (RSPCA Pet Guide)', 'hamster', '2015-05-07', 'HarperCollins UK', '109');
INSERT INTO books VALUES (default, 'Grace Fox Anderson', 'The Peanut Butter Hamster, and Other Animal Tails', 'hamster', '1979', 'Unknown', '136');
INSERT INTO books VALUES (default, 'Matthew Rayner', 'Hamster', 'hamster', '2004-01-04', 'Gareth Stevens Publishing LLLP', '36');
INSERT INTO books VALUES (default, 'T Albert', 'Hammy The Hamster', 'hamster', '2020-10-27', 'Unknown', '26');
INSERT INTO books VALUES (default, 'Fiona Watt', 'That''s Not My Hamster', 'hamster', '2012', 'Usborne Books', '0');
INSERT INTO books VALUES (default, 'Percy Parslow', 'Hamsters', 'hamster', '1989-09', 'TFH Publications', '132');
INSERT INTO books VALUES (default, 'Susanne Löhlein', 'Hamster Monster', 'hamster', '2014-08-01', 'NorthSouth Books', '0');
INSERT INTO books VALUES (default, 'G. L. Van Hoosier', 'Laboratory Hamsters', 'hamster', '1987-10-28', 'Elsevier', '420');
INSERT INTO books VALUES (default, 'Kass Reich', 'Up Hamster, Down Hamster', 'hamster', '2015-09-15', 'Orca Book Publishers', '25');
INSERT INTO books VALUES (default, 'HowExpert', 'How To Raise Hamsters', 'hamster', '2011-05-28', 'HowExpert', '79');
INSERT INTO books VALUES (default, 'Elaine Landau', 'Your Pet Hamster', 'hamster', '2007', 'Children''s Press(CT)', '0');
INSERT INTO books VALUES (default, 'Kathleen Tracy', 'The Hamster in Our Class', 'hamster', '2011-09-15', 'Mitchell Lane Publishers, Inc.', '36');
INSERT INTO books VALUES (default, 'Thorsten Hawk', 'My trusting hamster', 'hamster', '2022-01-06', 'epubli', '46');
INSERT INTO books VALUES (default, 'Astrid Desbordes', 'Travels of an Extraordinary Hamster', 'hamster', '2015', 'Unknown', '0');
INSERT INTO books VALUES (default, 'Jane Yates', 'Awesome Hamster Crafts', 'hamster', '2018-07-15', 'Gareth Stevens Publishing LLLP', '34');
INSERT INTO books VALUES (default, 'Michelle Markel', 'Hanukkah Hamster', 'hamster', '2018-09-15', 'Sleeping Bear Press', '36');
INSERT INTO books VALUES (default, 'Sue Fox', 'Hamsters', 'hamster', '2008-07', 'Unknown', '111');
INSERT INTO books VALUES (default, 'Michelle Hawkins', 'Hamster', 'hamster', '2021-01-11', 'Unknown', '34');
INSERT INTO books VALUES (default, 'Abby Klein', 'Stop that Hamster (Ready, Freddy! #12)', 'hamster', '2011-11-01', 'Scholastic Inc.', '81');
INSERT INTO books VALUES (default, 'Unknown', 'Einstein the Class Hamster and the Very Real Game Show', 'hamster', '2014-09-02', 'Macmillan', '177');
INSERT INTO books VALUES (default, 'Havelock McCreely', 'My Zombie Hamster', 'hamster', '2014-07-01', 'Carolrhoda Books', '210');
INSERT INTO books VALUES (default, 'Mick O''Hare', 'How to Fossilize Your Hamster', 'hamster', '2008-01-22', 'Macmillan', '260');
INSERT INTO books VALUES (default, 'Lynne Jonell', 'Hamster Magic', 'hamster', '2010', 'Random House Books for Young Readers', '114');
INSERT INTO books VALUES (default, 'Dave Lowe', 'My Hamster is a Genius', 'hamster', '2012', 'Lothian Children''s Books', '102');
INSERT INTO books VALUES (default, 'Ritsuko Kawai', 'Hamtaro Hamster Care Guide', 'hamster', '2002-12-10', 'Unknown', '64');
INSERT INTO books VALUES (default, 'Sharon Lynn Vanderlip', 'Dwarf Hamsters', 'hamster', '1999', 'Unknown', '103');
INSERT INTO books VALUES (default, 'Anita Ganeri', 'Hamsters', 'hamster', '2009', 'Capstone Classroom', '36');
INSERT INTO books VALUES (default, 'Troy D. Hibbitts', 'Texas Lizards', 'lizard', '2015-05-15', 'University of Texas Press', '352');
INSERT INTO books VALUES (default, 'Eric P. Pianka', 'Lizards', 'lizard', '2003-09-24', 'Univ of California Press', '698');
INSERT INTO books VALUES (default, 'Mark O''Shea', 'Lizards of the World', 'lizard', '2021-02-23', 'Ivy Press', '242');
INSERT INTO books VALUES (default, 'Gordon H. Rodda', 'Lizards of the World', 'lizard', '2020-09-01', 'JHU Press', '828');
INSERT INTO books VALUES (default, 'Sneed B. Collard III', 'Sneed B. Collard III''s Most Fun Book Ever About Lizards', 'lizard', '2012-02-01', 'Charlesbridge', '50');
INSERT INTO books VALUES (default, 'Mike Linley', 'The Lizard in the Jungle', 'lizard', '1988', 'Gareth Stevens Publishing', '32');
INSERT INTO books VALUES (default, 'Melissa Stewart', 'Salamander or Lizard?', 'lizard', '2011-01-01', 'Enslow Publishing, LLC', '26');
INSERT INTO books VALUES (default, 'Mark Pett', 'Lizard from the Park', 'lizard', '2015-09-08', 'Simon and Schuster', '44');
INSERT INTO books VALUES (default, 'Wade C. Sherbrooke', 'Introduction to Horned Lizards of North America', 'lizard', '2003-05-08', 'Univ of California Press', '192');
INSERT INTO books VALUES (default, 'Daniel Pinkwater', 'Lizard Music', 'lizard', '2011-01-25', 'New York Review of Books', '82');
INSERT INTO books VALUES (default, 'Richard D. Bartlett', 'Lizard Care from A to Z', 'lizard', '1997', 'B.E.S. Publishing', '188');
INSERT INTO books VALUES (default, 'Hobart Muir Smith', 'Handbook of Lizards', 'lizard', '1995', 'Comstock Publishing Associates', '0');
INSERT INTO books VALUES (default, 'Laurie J. Vitt', 'Lizard Ecology', 'lizard', '2014-07-14', 'Princeton University Press', '416');
INSERT INTO books VALUES (default, 'April Pulley Sayre', 'Like a Lizard', 'lizard', '2019-03-12', 'Astra Publishing House', '33');
INSERT INTO books VALUES (default, 'Russ Case', 'Lizards', 'lizard', '2006-09-01', 'Fox Chapel Publishing', '157');
INSERT INTO books VALUES (default, 'James Cherry', 'Loco for Lizards', 'lizard', '2000', 'Rising Moon (Nrl)', '68');
INSERT INTO books VALUES (default, 'Stanley F. Fox', 'Lizard Social Behavior', 'lizard', '2003-02-25', 'JHU Press', '476');
INSERT INTO books VALUES (default, 'Melinda Melton Crow', 'Little Lizard''s Family Fun', 'lizard', '2010', 'Capstone', '33');
INSERT INTO books VALUES (default, 'Stephen M. Reilly', 'Lizard Ecology', 'lizard', '2007-07-12', 'Cambridge University Press', '560');
INSERT INTO books VALUES (default, 'Melinda Melton Crow', 'Little Lizard''s New Friend', 'lizard', '2011', 'Capstone', '18');
INSERT INTO books VALUES (default, 'Rose Davin', 'Lizards', 'lizard', '2017-01-01', 'Capstone', '25');
INSERT INTO books VALUES (default, 'Mindy P. Kiernan', 'Lizards', 'lizard', '2014', 'Nova Science Publishers', '0');
INSERT INTO books VALUES (default, 'Raymond B. Huey', 'Lizard Ecology', 'lizard', '1983', 'Unknown', '501');
INSERT INTO books VALUES (default, 'Natalie Lunis', 'Black Spiny-Tailed Iguana', 'lizard', '2010-08-01', 'Bearport Publishing', '28');
INSERT INTO books VALUES (default, 'Dorothy Hinshaw Patent', 'The Lizard Scientists', 'lizard', '2022-12-13', 'HarperCollins', '79');
INSERT INTO books VALUES (default, 'Daniel David Beck', 'Biology of Gila Monsters and Beaded Lizards', 'lizard', '2005', 'Univ of California Press', '260');
INSERT INTO books VALUES (default, 'Susan Kralovansky', 'Salamander Or Lizard?', 'lizard', '2014-07', 'Super Sandcastle', '0');
INSERT INTO books VALUES (default, 'Jan Sovak', 'Lizards', 'lizard', '2006-03-24', 'Courier Corporation', '36');
INSERT INTO books VALUES (default, 'Mari Schuh', 'Lizard or Salamander?', 'lizard', '2024-09-17', 'Blastoff! Readers', '24');
INSERT INTO books VALUES (default, 'Sherburn R. Sanborn', 'The Lizard Watching Guide', 'lizard', '1994-01-01', 'Sherby Sanborn Nature', '36');
INSERT INTO books VALUES (default, 'Donald W. Tinkle', 'The Life and Demography of the Side Blotched Lizard, Uta Stansburiana', 'lizard', '1967', 'Unknown', '192');
INSERT INTO books VALUES (default, 'Marta Magellan', 'Those Lively Lizards', 'lizard', '2008-09-01', 'Pineapple Press', '57');
INSERT INTO books VALUES (default, 'Ralph E. Molnar', 'Dragons in the Dust', 'lizard', '2004-03-30', 'Indiana University Press', '346');
INSERT INTO books VALUES (default, 'Edwin Johns', 'Lizzie''s Lizard Set(Level 4)', 'lizard', '1998', 'McGraw-Hill', '24');
INSERT INTO books VALUES (default, 'Anne Richards', 'Caring for Our Lizard', 'lizard', '2015-10', 'Creative Teaching Press', '20');
INSERT INTO books VALUES (default, 'Philippe De Vosjoli', 'The Lizard Keeper''s Handbook', 'lizard', '1994', 'Unknown', '182');
INSERT INTO books VALUES (default, 'Banana Yoshimoto', 'Lizard', 'lizard', '1996-03', 'Simon and Schuster', '195');
INSERT INTO books VALUES (default, 'Pat Jacobs', 'Lizard Pals', 'lizard', '2018-12-31', 'Pet Pals', '0');
INSERT INTO books VALUES (default, 'Roberto Betances', 'Lizard Blood', 'lizard', '2014-12-15', 'Gareth Stevens Publishing LLLP', '26');
INSERT INTO books VALUES (default, 'Marty Crump', 'Eye of Newt and Toe of Frog, Adder''s Fork and Lizard''s Leg', 'lizard', '2015-11-16', 'University of Chicago Press', '329');
INSERT INTO books VALUES (default, 'Alexander Wilensky', 'The Splendid Spotted Snake', 'snake', '2011-09-29', 'Workman Publishing', '19');
INSERT INTO books VALUES (default, 'Keith Baker', 'Hide and Snake', 'snake', '1991', 'Houghton Mifflin Harcourt', '44');
INSERT INTO books VALUES (default, 'David A. Steen', 'Secrets of Snakes', 'snake', '2019-09-23', 'Texas A&M University Press', '186');
INSERT INTO books VALUES (default, 'Mark O''Shea', 'The Book of Snakes', 'snake', '2018-10-15', 'University of Chicago Press', '657');
INSERT INTO books VALUES (default, 'Jamie James', 'The Snake Charmer', 'snake', '2008-06-03', 'Grand Central Publishing', '312');
INSERT INTO books VALUES (default, 'Renata Allen', 'The Girl and the Snake and Other Short Plays', 'snake', '1996', 'Heinemann', '136');
INSERT INTO books VALUES (default, 'John Rossi', 'What''s Wrong with My Snake?', 'snake', '2007-02-15', 'BowTie Press', '162');
INSERT INTO books VALUES (default, 'David L. Kimbrough', 'Taking Up Serpents', 'snake', '2002', 'Mercer University Press', '592');
INSERT INTO books VALUES (default, 'Libba Moore Gray', 'Small Green Snake', 'snake', '1997-09-01', 'Scholastic', '32');
INSERT INTO books VALUES (default, 'Russ Case', 'Snakes', 'snake', '2007-10-01', 'Fox Chapel Publishing', '153');
INSERT INTO books VALUES (default, 'Chris Mattison', 'Snake', 'snake', '2016-03-15', 'National Geographic Books', '0');
INSERT INTO books VALUES (default, 'Whit Gibbons', 'Snakes of the Eastern United States', 'snake', '2017-04-15', 'University of Georgia Press', '426');
INSERT INTO books VALUES (default, 'Cate Foley', 'Find the Snake', 'snake', '2000-03', 'Turtleback Books', '24');
INSERT INTO books VALUES (default, 'Melissa Stewart', 'National Geographic Readers: Snakes', 'snake', '2011-07-05', 'National Geographic Society', '36');
INSERT INTO books VALUES (default, 'Kate Jennings', 'Snake', 'snake', '2011-03-28', 'Black Inc.', '116');
INSERT INTO books VALUES (default, 'Top That', 'Sammy the Snake', 'snake', '2008-05', 'Tide Mill Press', '0');
INSERT INTO books VALUES (default, 'Houghton Mifflin Harcourt', 'Snake Goes Away', 'snake', '2007', 'Literacy by Design', '16');
INSERT INTO books VALUES (default, 'Ted Levin', 'America''s Snake', 'snake', '2016-05-12', 'University of Chicago Press', '508');
INSERT INTO books VALUES (default, 'Alan Tennant', 'Snakes of North America', 'snake', '2003-06-19', 'Taylor Trade Publishing', '636');
INSERT INTO books VALUES (default, 'James R. Dixon', 'Texas Snakes', 'snake', '2005-11-01', 'University of Texas Press', '386');
INSERT INTO books VALUES (default, 'Kelly Tills', 'Snakes Have No Legs', 'snake', '2021-09-21', 'Awesome Animals', '28');
INSERT INTO books VALUES (default, 'John Rossi', 'What''s Wrong With My Snake? (advanced Vivarium Systems)', 'snake', '2016-11-22', 'Fox Chapel Publishing', '161');
INSERT INTO books VALUES (default, 'Walter Hough', 'The Moki Snake Dance', 'snake', '1901', 'Unknown', '72');
INSERT INTO books VALUES (default, 'John Godey', 'THE SNAKE', 'snake', '1978', 'Unknown', '204');
INSERT INTO books VALUES (default, 'Ann Lawrence', 'Snakes', 'snake', '2015-12-01', 'Unknown', '74');
INSERT INTO books VALUES (default, 'Larry Slawson', 'The Top 10 Strangest Snakes in the World', 'snake', '2022-01-03', 'Larry Slawson', '30');
INSERT INTO books VALUES (default, 'Michael Wayne Caldwell', 'The Origin of Snakes', 'snake', '2019-06-28', 'CRC Press', '327');
INSERT INTO books VALUES (default, 'Harry W. Greene', 'Snakes', 'snake', '1997', 'Univ of California Press', '382');
INSERT INTO books VALUES (default, 'Deben Delhay', 'The Encyclopedia of Snake Species', 'snake', '2009', 'Unknown', '200');
INSERT INTO books VALUES (default, 'Sasha Nanua', 'Sisters of the Snake', 'snake', '2021-06-15', 'HarperCollins', '451');
INSERT INTO books VALUES (default, 'Karen Latchana Kenney', 'Life Cycle of a Snake', 'snake', '2018', 'Incredible Animal Life Cycles', '24');
INSERT INTO books VALUES (default, 'Zai Whitaker', 'Kali and the Rat Snake', 'snake', '2006', 'Kane/Miller Book Publishers, Inc.', '19');
INSERT INTO books VALUES (default, 'Ludwig Trutnau', 'Nonvenomous Snakes', 'snake', '1986', 'Barron''s Educational Series', '200');
INSERT INTO books VALUES (default, 'Andrew T. Holycross', 'Snakes of Arizona', 'snake', '2020-11', 'Unknown', '0');
INSERT INTO books VALUES (default, 'Daniel Gilpin', 'Snakes', 'snake', '2007', 'Parragon Pubishing India', '104');
INSERT INTO books VALUES (default, 'Department of the Navy Bureau of Medicine and Surgery', 'Venomous Snakes of the World', 'snake', '2013-09-01', 'Simon and Schuster', '688');
INSERT INTO books VALUES (default, 'Camilla de la Bedoyere', 'Stop! Snake!', 'snake', '2021-08', 'Qeb Publishing -- Quarto Library', '32');
INSERT INTO books VALUES (default, 'Mavis Smith', 'A Snake Mistake', 'snake', '1998-07', 'Perfection Learning', '0');
INSERT INTO books VALUES (default, 'John A. Burton', 'The Book of Snakes', 'snake', '1991', 'Gramercy', '148');
INSERT INTO books VALUES (default, 'Hideyo Noguchi', 'Snake Venoms', 'snake', '1909', 'Unknown', '452');
INSERT INTO books VALUES (default, 'Les Beletsky', 'Bird Songs', 'bird', '2018-10-16', 'becker&mayer! Books', '371');
INSERT INTO books VALUES (default, 'Sidney Wade', 'Bird Book', 'bird', '2017-09-05', 'Unknown', '100');
INSERT INTO books VALUES (default, 'Anne Lamott', 'Bird by Bird', 'bird', '1994', 'Anchor', '239');
INSERT INTO books VALUES (default, 'Thornton W. Burgess', 'The Burgess Bird Book for Children', 'bird', '2003-03-10', 'Courier Corporation', '274');
INSERT INTO books VALUES (default, 'Unknown', 'Bird', 'bird', '2013-10-22', 'Chronicle Books', '298');
INSERT INTO books VALUES (default, 'Pete Dunne', 'Hawks in Flight', 'bird', '2012', 'Mariner Books', '0');
INSERT INTO books VALUES (default, 'Jerry Pallotta', 'The Bird Alphabet Book', 'bird', '2016-05-03', 'Charlesbridge', '34');
INSERT INTO books VALUES (default, 'Jeremy Tankard', 'Boo Hoo Bird', 'bird', '2009', 'Scholastic Inc.', '34');
INSERT INTO books VALUES (default, 'John Ham', 'Kitchen Table Bird Book', 'bird', '1995', 'Thunder Bay Press (MI)', '0');
INSERT INTO books VALUES (default, 'Jennifer Ward', 'How to Find a Bird', 'bird', '2020-08-04', 'Simon and Schuster', '48');
INSERT INTO books VALUES (default, 'David Cunliffe', 'Whoever Heard of a Flying Bird?', 'bird', '2020-08-31', 'Unknown', '0');
INSERT INTO books VALUES (default, 'Frank Gallo', 'Hear and There Book: Bird Calls', 'bird', '2001-04-01', 'Innovative Kids', '0');
INSERT INTO books VALUES (default, 'Kenn Kaufman', 'Kaufman Field Guide to Birds of North America', 'bird', '2005', 'Houghton Mifflin Harcourt', '396');
INSERT INTO books VALUES (default, 'David Allen Sibley', 'What It''s Like to Be a Bird', 'bird', '2020-04-14', 'Knopf', '241');
INSERT INTO books VALUES (default, 'Matt Kracht', 'The Field Guide to Dumb Birds of North America', 'bird', '2019-04-02', 'Chronicle Books', '178');
INSERT INTO books VALUES (default, 'Zetta Elliott', 'Bird', 'bird', '2008', 'Lee & Low Books', '0');
INSERT INTO books VALUES (default, 'Thornton W. Burgess', 'The Burgess Animal Book for Children', 'bird', '2012-05-14', 'Courier Corporation', '290');
INSERT INTO books VALUES (default, 'John James Audubon', 'The Birds of America', 'bird', '2013', 'White Lion Publishing', '0');
INSERT INTO books VALUES (default, 'Patricia Anne Davis', 'Brian''s Bird', 'bird', '2000', 'Prairie Paperbacks', '40');
INSERT INTO books VALUES (default, 'Dan Gemeinhart', 'The Remarkable Journey of Coyote Sunrise', 'bird', '2019-01-08', 'Henry Holt and Company (BYR)', '351');
INSERT INTO books VALUES (default, 'Natalia Balo', 'Bird Anatomy for Artists', 'bird', '2019-08', 'Unknown', '128');
INSERT INTO books VALUES (default, 'Angus Hyland', 'The Book of the Bird', 'bird', '2016-05-31', 'Laurence King Publishing', '0');
INSERT INTO books VALUES (default, 'Irby J. Lovette', 'Handbook of Bird Biology', 'bird', '2016-06-27', 'John Wiley & Sons', '733');
INSERT INTO books VALUES (default, 'Ed Vere', 'Max and Bird', 'bird', '2016-06-02', 'Penguin UK', '41');
INSERT INTO books VALUES (default, 'Nathan Emery', 'Bird Brain', 'bird', '2016-08-23', 'Princeton University Press', '195');
INSERT INTO books VALUES (default, 'John James Audubon', 'The Birds of America', 'bird', '1842', 'Unknown', '476');
INSERT INTO books VALUES (default, 'Rodney Stotts', 'Bird Brother', 'bird', '2022-02-03', 'Island Press', '226');
INSERT INTO books VALUES (default, 'Stephen King', 'On Writing', 'bird', '2012', 'Hodder & Stoughton', '351');
INSERT INTO books VALUES (default, 'David Allen Sibley', 'The Sibley Guide to Bird Life & Behavior', 'bird', '2009', 'Alfred a Knopf Incorporated', '588');
INSERT INTO books VALUES (default, 'Lisl H. Detlefsen', 'Time for Cranberries', 'bird', '2015-09', 'Macmillan', '34');
INSERT INTO books VALUES (default, 'Mabel Osgood Wright', 'Citizen Bird', 'bird', '1897', 'Unknown', '460');
INSERT INTO books VALUES (default, 'Andrea Pinnington', 'The Little Book of Woodland Bird Songs', 'bird', '2018-09-25', 'Unknown', '0');
INSERT INTO books VALUES (default, 'Lizzy Rockwell', 'A Bird Is a Bird', 'bird', '2015-02-01', 'National Geographic Books', '0');
INSERT INTO books VALUES (default, 'Ralph Hoffmann', 'Common Birds: Second Series', 'bird', '1900', 'Unknown', '36');
INSERT INTO books VALUES (default, 'Josep del Hoyo', 'All the Birds of the World', 'bird', '2020', 'Unknown', '967');
INSERT INTO books VALUES (default, 'Alex Branson', 'Water, Wasted', 'bird', '2020-11-10', 'Unknown', '288');
INSERT INTO books VALUES (default, 'Jim Carpenter', 'The Joy of Bird Feeding', 'bird', '2017', 'Unknown', '0');
INSERT INTO books VALUES (default, 'Roni Horn', 'Bird', 'bird', '2008', 'Steidl / Edition7L', '36');
INSERT INTO books VALUES (default, 'Frank Bello', 'Fathers, Brothers, and Sons: Surviving Anguish, Abandonment, and Anthrax', 'bird', '2022-12-06', 'Unknown', '0');
INSERT INTO books VALUES (default, 'Chip Jacobs', 'Arroyo', 'bird', '2019-10-15', 'Unknown', '0');
